[workspace]
authors = ["Johannes Koester <johannes.koester@uni-due.de>"]
channels = ["conda-forge", "bioconda"]
name = "snakemake-plugin-catalog"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "sphinx-build source build"
build-single = { cmd = "sphinx-build source build", env = { TEST_PACKAGES = "snakemake-executor-plugin-cluster-generic" }}
qc = "ruff format --check && ruff check"
apply-qc = "ruff format && ruff check --fix"

[dependencies]
sphinx = ">=8.3.0,<9"
python = "3.11.*"
ratelimit = ">=2.2.1,<3"
m2r2 = ">=0.3.4,<0.4"
cmake = ">=4.1.1,<5"
gcc_linux-64 = ">=15.1.0,<16"
pkgconfig = ">=1.5.5,<2"
ruff = ">=0.12.11,<0.13"

[pypi-dependencies]
sphinxawesome-theme = ">=5.3.2, <6"
pypi-simple = ">=1.7.0, <2"
